[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
treasury = "EYpZP5URZyGy32ZaHewPRe3S2BBXBAbtqNfyA5GxphUA"
agent_registry = "9vqS7h8TMjuu7cuzdh6NLzG4JikDi6r1saaxZdTtByYJ"
prediction_market = "DR9aDNjhEwKmw3KmNkLiNM7Kw8mspMw4KzdhR9xXAFWP"

[programs.devnet]
treasury = "EYpZP5URZyGy32ZaHewPRe3S2BBXBAbtqNfyA5GxphUA"
agent_registry = "9vqS7h8TMjuu7cuzdh6NLzG4JikDi6r1saaxZdTtByYJ"
prediction_market = "DR9aDNjhEwKmw3KmNkLiNM7Kw8mspMw4KzdhR9xXAFWP"

[programs.mainnet]
treasury = "EYpZP5URZyGy32ZaHewPRe3S2BBXBAbtqNfyA5GxphUA"
agent_registry = "9vqS7h8TMjuu7cuzdh6NLzG4JikDi6r1saaxZdTtByYJ"
prediction_market = "DR9aDNjhEwKmw3KmNkLiNM7Kw8mspMw4KzdhR9xXAFWP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"

[[test.validator.clone]]
address = "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4"

[[test.validator.clone]]
address = "KAm5x66KFgQKQWJHNu5T8ucpT9cPE2XvKaFBeW1YWE2"
