[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
treasury = "BovzoaAX7fivhW2RS9juginL3MQmT3x6tpFUwB7tjST7"
agent_registry = "2fs7z5NAojSAgJkg3yQz5EgjBXki9tFK6sGRHVMvQfpq"
prediction_market = "FT89ecUFydzZsT495pcGVdnPqm5ZBxLEagaYbBMYbLUX"

[programs.devnet]
treasury = "BovzoaAX7fivhW2RS9juginL3MQmT3x6tpFUwB7tjST7"
agent_registry = "2fs7z5NAojSAgJkg3yQz5EgjBXki9tFK6sGRHVMvQfpq"
prediction_market = "FT89ecUFydzZsT495pcGVdnPqm5ZBxLEagaYbBMYbLUX"

[programs.mainnet]
treasury = "BovzoaAX7fivhW2RS9juginL3MQmT3x6tpFUwB7tjST7"
agent_registry = "2fs7z5NAojSAgJkg3yQz5EgjBXki9tFK6sGRHVMvQfpq"
prediction_market = "FT89ecUFydzZsT495pcGVdnPqm5ZBxLEagaYbBMYbLUX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"

[[test.validator.clone]]
address = "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4"

[[test.validator.clone]]
address = "KAm5x66KFgQKQWJHNu5T8ucpT9cPE2XvKaFBeW1YWE2"
